
const $=s=>document.querySelector(s); const $$=s=>Array.from(document.querySelectorAll(s));
const state={user:null,trips:[],data:{},activeTripId:''};
function apiUrl(){return (window.APP_CONFIG&&APP_CONFIG.API_URL)||''}
function uid(){return Math.random().toString(36).slice(2,8).toUpperCase()}
function toast(msg,type='msg'){const el=$('#msg'); if(!el)return alert(msg); el.className=type; el.textContent=msg; setTimeout(()=>{el.textContent='';el.className=''},5000)}
async function api(action,payload={}){ if(!apiUrl()||apiUrl().includes('PASTE_')) throw new Error('ضع رابط Apps Script في config.js'); const body={action,...payload,token:localStorage.umrah_token||''}; try{const r=await fetch(apiUrl(),{method:'POST',body:JSON.stringify(body),headers:{'Content-Type':'text/plain;charset=utf-8'}}); return await r.json()}catch(e){const qs=new URLSearchParams({payload:JSON.stringify(body)}); const r=await fetch(apiUrl()+'?'+qs); return await r.json()} }
function session(){try{return JSON.parse(localStorage.umrah_user||'null')}catch(e){return null}}
function requireLogin(){state.user=session(); if(!state.user){location.href='index.html';return false} $('#who').textContent=state.user.name+' - '+state.user.role; return true}
async function login(){try{const username=$('#username').value.trim(), password=$('#password').value; const res=await api('login',{username,password}); if(!res.ok) return toast(res.error||'فشل الدخول','err'); localStorage.umrah_user=JSON.stringify(res.user); localStorage.umrah_token=res.token; location.href=res.user.role==='Pilgrim'?'portal.html':'admin.html'}catch(e){toast(e.message,'err')}}
function logout(){localStorage.clear();location.href='index.html'}
function setTabs(){ $$('.tab').forEach(b=>b.onclick=()=>{ $$('.tab').forEach(x=>x.classList.remove('active')); b.classList.add('active'); $$('.panel').forEach(p=>p.classList.add('hidden')); $('#'+b.dataset.tab).classList.remove('hidden')}) }
function val(id){return $('#'+id)?.value?.trim()||''} function formObj(ids){let o={}; ids.forEach(id=>o[id]=val(id)); return o}
async function loadAll(){const res=await api('getAll'); if(!res.ok) return toast(res.error,'err'); state.data=res.data; state.trips=res.data.Trips||[]; fillTrips(); renderDashboard(); renderAll();}
function fillTrips(){const opts='<option value="">كل الرحلات</option>'+state.trips.map(t=>`<option value="${t.tripId}">${t.tripName||t.tripId}</option>`).join(''); $$('.tripSelect').forEach(s=>{const old=s.value;s.innerHTML=opts;s.value=old||state.activeTripId});}
function rows(name){return state.data[name]||[]} function byTrip(arr){const tid=$('#filterTrip')?.value||''; return tid?arr.filter(x=>x.tripId===tid):arr}
function renderDashboard(){const tid=$('#filterTrip')?.value||''; const pilgrims=byTrip(rows('Pilgrims')); const payments=byTrip(rows('Payments')); const expenses=byTrip(rows('Expenses')); const visas=byTrip(rows('Visas')); const buses=byTrip(rows('Buses')); const pay=payments.reduce((s,x)=>s+num(x.amountUSD),0); const exp=expenses.reduce((s,x)=>s+num(x.amountUSD),0); $('#stats').innerHTML=[['المعتمرون',pilgrims.length],['الدفعات USD',pay.toFixed(2)],['المصاريف USD',exp.toFixed(2)],['الربح/الخسارة', (pay-exp).toFixed(2)],['تأشيرات صادرة',visas.filter(v=>v.status==='صادرة').length],['الباصات',buses.length]].map(x=>`<div class="stat"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('')}
function num(v){return Number(v||0)||0}
function table(el, arr, cols, actions){$(el).innerHTML=`<table><thead><tr>${cols.map(c=>`<th>${c[1]}</th>`).join('')}${actions?'<th>إجراءات</th>':''}</tr></thead><tbody>${arr.map(r=>`<tr>${cols.map(c=>`<td>${fmt(r[c[0]],c[0])}</td>`).join('')}${actions?`<td>${actions(r)}</td>`:''}</tr>`).join('')}</tbody></table>`}
function fmt(v,k){if(k&&k.toLowerCase().includes('status')){let cls=(v==='صادرة'||v==='مكتمل'||v==='مدفوع'||v==='عاد'||v==='حاضر')?'ok':(v==='مرفوض'||v==='متأخر'||v==='نازل ولم يعد'?'bad':'warnpill');return `<span class="pill ${cls}">${v||''}</span>`} return v||''}
function renderAll(){renderDashboard(); table('#tripsTable',rows('Trips'),[['tripId','الكود'],['tripName','الرحلة'],['tripType','النوع'],['startDate','الذهاب'],['endDate','العودة'],['baseCurrency','الأساس'],['status','الحالة']]); table('#pilgrimsTable',byTrip(rows('Pilgrims')),[['pilgrimCode','الكود'],['fullName','الاسم'],['phone','الهاتف'],['nationality','الجنسية'],['familyId','العائلة'],['packageName','الباقة'],['passportStatus','الجواز'],['visaStatus','التأشيرة'],['balanceUSD','الرصيد USD']],r=>`<button class="btn light" onclick="printCard('${r.pilgrimCode}')">بطاقة</button>`); table('#paymentsTable',byTrip(rows('Payments')),[['paymentId','رقم'],['pilgrimCode','المعتمر'],['date','التاريخ'],['currency','عملة'],['amount','المبلغ'],['rateToUSD','الصرف'],['amountUSD','USD'],['method','طريقة'],['note','ملاحظة']]); table('#expensesTable',byTrip(rows('Expenses')),[['expenseId','رقم'],['date','التاريخ'],['category','التصنيف'],['currency','عملة'],['amount','المبلغ'],['rateToUSD','الصرف'],['amountUSD','USD'],['paidBy','دفع بواسطة'],['note','ملاحظة']]); table('#visasTable',byTrip(rows('Visas')),[['visaId','رقم'],['pilgrimCode','المعتمر'],['passportNo','الجواز'],['status','الحالة'],['requestDate','طلب'],['issueDate','إصدار'],['note','ملاحظة']]); table('#hotelsTable',byTrip(rows('Hotels')),[['hotelId','رقم'],['city','المدينة'],['hotelName','الفندق'],['checkIn','دخول'],['checkOut','خروج'],['nights','ليالي']]); table('#roomsTable',byTrip(rows('Rooms')),[['roomId','رقم'],['hotelId','الفندق'],['roomNo','الغرفة'],['roomType','نوع'],['capacity','سعة'],['assignedCount','مسكن']]); table('#busesTable',byTrip(rows('Buses')),[['busId','رقم'],['busNo','الباص'],['company','الشركة'],['driverName','السائق'],['guideName','المشرف'],['capacity','سعة']]); table('#stopsTable',byTrip(rows('BusStops')),[['stopId','رقم'],['busId','باص'],['stopName','التوقف'],['time','الوقت'],['status','الحالة'],['outCount','نزل'],['backCount','عاد']]); table('#guidesTable',byTrip(rows('Guides')),[['guideId','رقم'],['guideName','المرشد'],['phone','هاتف'],['language','لغة'],['maxPilgrims','حد'],['advanceBalanceUSD','عهدة USD']]); table('#notifyTable',byTrip(rows('Notifications')),[['noticeId','رقم'],['title','العنوان'],['target','الهدف'],['body','النص'],['createdAt','تاريخ']]); table('#reqTable',byTrip(rows('Requirements')),[['reqId','رقم'],['itemName','البند'],['qtyPerPilgrim','لكل معتمر'],['totalQty','الإجمالي'],['status','الحالة']]); table('#attendanceTable',byTrip(rows('Attendance')),[['attId','رقم'],['date','التاريخ'],['pilgrimCode','المعتمر'],['place','المكان'],['status','الحالة']]); table('#complaintsTable',byTrip(rows('Complaints')),[['complaintId','رقم'],['pilgrimCode','المعتمر'],['category','تصنيف'],['status','الحالة'],['description','الوصف'],['createdAt','تاريخ']]); }
async function save(action, ids){try{const data=formObj(ids); const res=await api(action,{data}); if(!res.ok)return toast(res.error,'err'); toast('تم الحفظ','success'); await loadAll()}catch(e){toast(e.message,'err')}}
async function addPayment(){let data=formObj(['tripId','pilgrimCode','date','currency','amount','rateToUSD','method','note']); data.amountUSD=(num(data.amount)*num(data.rateToUSD)).toFixed(2); await saveDirect('addPayment',data)}
async function addExpense(){let data=formObj(['tripId','date','category','currency','amount','rateToUSD','paidBy','note']); data.amountUSD=(num(data.amount)*num(data.rateToUSD)).toFixed(2); await saveDirect('addExpense',data)}
async function saveDirect(action,data){try{const res=await api(action,{data}); if(!res.ok)return toast(res.error,'err'); toast('تم الحفظ','success'); await loadAll()}catch(e){toast(e.message,'err')}}
async function smartDistribute(){const tripId=$('#filterTrip').value||val('distTripId'); if(!tripId)return toast('اختر رحلة','err'); const res=await api('smartDistribute',{tripId}); if(!res.ok)return toast(res.error,'err'); toast(res.message,'success'); await loadAll()}
function printCard(code){const p=rows('Pilgrims').find(x=>x.pilgrimCode===code); if(!p)return; const w=window.open('','_blank'); w.document.write(`<html dir="rtl"><head><title>بطاقة معتمر</title><style>body{font-family:Tahoma;padding:25px}.card{border:2px solid #111;border-radius:18px;padding:20px;width:420px}h2{margin:0 0 15px}.qr{font-size:42px;text-align:center;border:1px dashed #999;padding:20px;margin-top:15px}</style></head><body><div class="card"><h2>بطاقة معتمر</h2><p><b>الاسم:</b> ${p.fullName}</p><p><b>الكود:</b> ${p.pilgrimCode}</p><p><b>الهاتف:</b> ${p.phone||''}</p><p><b>الباقة:</b> ${p.packageName||''}</p><p><b>الجواز:</b> ${p.passportStatus||''}</p><p><b>التأشيرة:</b> ${p.visaStatus||''}</p><div class="qr">${p.pilgrimCode}</div></div><script>print()</script></body></html>`)}
async function initAdmin(){if(!requireLogin())return; setTabs(); $('#filterTrip').onchange=renderAll; await loadAll()}
async function initPortal(){state.user=session(); if(!state.user){location.href='index.html';return} $('#who').textContent=state.user.name; const res=await api('getPortal'); if(!res.ok)return toast(res.error,'err'); const d=res.data; $('#portal').innerHTML=`<div class="card"><h2>${d.pilgrim.fullName}</h2><p>الكود: <b>${d.pilgrim.pilgrimCode}</b></p><p>التأشيرة: ${fmt(d.pilgrim.visaStatus,'status')}</p><p>الجواز: ${fmt(d.pilgrim.passportStatus,'status')}</p><p>الرصيد USD: <b>${d.pilgrim.balanceUSD||0}</b></p><p>رابط الملف: ${d.pilgrim.driveLink?`<a href="${d.pilgrim.driveLink}" target="_blank">فتح</a>`:'-'}</p></div>`; table('#portalPayments',d.payments||[],[['date','التاريخ'],['currency','عملة'],['amount','المبلغ'],['amountUSD','USD'],['method','طريقة']]); table('#portalNotices',d.notifications||[],[['title','العنوان'],['body','النص'],['createdAt','التاريخ']]);}
window.addEventListener('DOMContentLoaded',()=>{ if($('#loginBtn'))$('#loginBtn').onclick=login; if($('#adminApp'))initAdmin(); if($('#portalApp'))initPortal(); });
